config/routes.rb
Rails.application.routes.draw do


  get 'bookings/search'
  post 'bookings/search', to: 'bookings#search_post'
  get 'bookings/bookroom'
  get '/roomhistory/:id', to: 'bookings#roomhistory',  via: :get, as: :room_history
  get '/userhistory/:id', to: 'bookings#userhistory', via: :get, as: :user_history
  get '/index_admin', to: 'library_members#index_admin'
  get '/new_admin', to: 'library_members#new_admin'
  get '/new_admin_library_member', to: 'library_members#new_admin_library_member'
  post '/index_admin', to: 'library_members#create_admin'
  resources :bookings
  resources :rooms
  get 'sessions/new'
  #get 'library_members/new'
  resources :library_members
  get 'static_pages/home'
  get  '/signup',  to: 'library_members#new'
  get 'static_pages/help'
  get 'static_pages/about'
  root 'static_pages#home'
  post '/signup',  to: 'library_members#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/library_member.rb
class LibraryMember < ApplicationRecord
  has_many :bookings, :dependent => :delete_all
  has_secure_password
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  def LibraryMember.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/library_members_controller.rb
class LibraryMembersController < ApplicationController
  before_action :correct_library_member,   only: [:edit, :update]
  before_action :logged_in_library_member, only: [:index, :edit, :update, :destroy]
  before_action :admin_user,     only: :destroy

  def index_admin
    @library_members = LibraryMember.where(admin: true)
  end

  def index
    @library_members = LibraryMember.all
  end
  def new
    @library_member = LibraryMember.new
  end
  def new_admin
    @library_member = LibraryMember.new
  end
  def new_admin_library_member
    @library_member = LibraryMember.new
  end

  def show
    @library_member = LibraryMember.find(params[:id])
  end

  def create
    if params[:library_member][:admin] =='true'
      params[:library_member][:admin]=true
    end
    @library_member = LibraryMember.new(library_member_params)
    if @library_member.save
      # log_in @library_member
      flash[:success] = "Welcome to the NC State Library App!"
      redirect_to @library_member
    else
      render 'new'
    end
  end
  def edit
    @library_member = LibraryMember.find(params[:id])
  end

  def update
    @library_member = LibraryMember.find(params[:id])
    if @library_member.update_attributes(library_member_params)
      flash[:success] = "Profile updated"
      redirect_to @library_member
    else
      render 'edit'
    end
  end

  def destroy
    LibraryMember.find(params[:id]).destroy
    flash[:success] = "Library Member deleted"
    redirect_to library_members_url
  end




  private

  def library_member_params
    params.require(:library_member).permit(:name, :email, :password,
                                 :password_confirmation,:admin)
  end

  def logged_in_library_member
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  def correct_library_member
    @library_member = LibraryMember.find(params[:id])
    redirect_to(root_url) unless current_user?(@library_member)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/library_members_helper.rb
module LibraryMembersHelper
end

app/views/library_members/_form.html.erb
<%= form_for(@library_member) do |f| %>
    <%= render 'shared/error_messages', object: @library_member %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/library_members/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

  </div>
</div>

app/views/library_members/index.html.erb
<% provide(:title, 'All Library Members') %>
<h1>All Library Members</h1>

<ul class="library_members">
  <% @library_members.each do |library_member| %>
      <li>
        <%= link_to library_member.name, library_member %>
        <%= library_member.email %>
        <% if library_member.admin %>
          <%= "Admin" %>
            <% else %>
        <%= "Member" %>
            <% end %>
        <% if current_user.admin? && !current_user?(library_member) && library_member.id != 1%>
            | <%= link_to "delete", library_member, method: :delete,
                          data: { confirm: "You sure?" } %>
        <% end %>
      </li>
  <% end %>
</ul>
<br>
<%= link_to 'Create Members', new_library_member_path %>

app/views/library_members/index_admin.html.erb
<% provide(:title, 'Admins') %>
<h1>Admins</h1>
<ul class="library_members">
  <% @library_members.each do |library_member| %>
      <li>
        <%= link_to library_member.name, library_member %>
        <%= library_member.email %>
        <% if current_user.admin? && !current_user?(library_member)&& library_member.id!=1 %>
            | <%= link_to "delete", library_member, method: :delete,
                          data: { confirm: "You sure?" } %>
        <% end %>
      </li>
  <% end %>
</ul>

app/views/library_members/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<% if not logged_in? %>
  <h1>Sign up</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
    </div>
  </div>
<% else %>
    <center><h3>Looks like you are already logged in, please log out first to sign up!</h3>
      </center>
<% end %>

app/views/library_members/new_admin.html.erb
<% provide(:title, 'Create a new Admin') %>
<% provide(:button_text, 'Create Admin') %>
<% if logged_in? %>
    <h1>Create a new Admin</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@library_member) do |f| %>
            <%= render 'shared/error_messages', object: @library_member %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.label :admin %>
            <%= f.hidden_field :admin, :value => true %>
            <%= f.submit yield(:button_text), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
<% else %>
    <center>
    </center>
<% end %>

app/views/library_members/new_admin_library_member.html.erb
<% provide(:title, 'Create a new Member') %>
<% provide(:button_text, 'Create Member') %>
<% if logged_in? %>
    <h1>Create a new Library Member</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@library_member) do |f| %>
            <%= render 'shared/error_messages', object: @library_member %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit yield(:button_text), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
<% else %>
    <center>
    </center>
<% end %>

app/views/library_members/show.html.erb
<%= @library_member.name %>, <%= @library_member.email %>
<p>
<td><%= link_to 'History', user_history_path %></td>
</p>