config/routes.rb
Rails.application.routes.draw do


  get 'bookings/search'
  post 'bookings/search', to: 'bookings#search_post'
  get 'bookings/bookroom'
  get '/roomhistory/:id', to: 'bookings#roomhistory',  via: :get, as: :room_history
  get '/userhistory/:id', to: 'bookings#userhistory', via: :get, as: :user_history
  get '/index_admin', to: 'library_members#index_admin'
  get '/new_admin', to: 'library_members#new_admin'
  get '/new_admin_library_member', to: 'library_members#new_admin_library_member'
  post '/index_admin', to: 'library_members#create_admin'
  resources :bookings
  resources :rooms
  get 'sessions/new'
  #get 'library_members/new'
  resources :library_members
  get 'static_pages/home'
  get  '/signup',  to: 'library_members#new'
  get 'static_pages/help'
  get 'static_pages/about'
  root 'static_pages#home'
  post '/signup',  to: 'library_members#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :library_member
  attr_accessor :emails
  validate :start_and_end_date_validation, :end_date_validation, :no_of_hours, :start_date_validation
  def start_and_end_date_validation
    if self.start > self.end
      errors.add(:start, "time should be less than End time")
    end
  end
  def start_date_validation
    if self.start < DateTime.now() - 4.hours
      errors.add(:start, "time should greater than current time")
    end
  end
  def no_of_hours
    if ((self.end - self.start) / 1.hour).round > 2.hour
      errors.add(:start, "You cannot book room for more than 2 hours")
    end
  end
  def end_date_validation
    if self.end > 7.days.from_now - 4.hours
      errors.add(:booking, "time should be less than 7 days")
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  def search
    @rooms = []
    if params.has_key?(:start_time)
      @duration = params[:duration]
      @size = params[:size]
      @building = params[:building]
      @search_start_time = DateTime.new(params[:start_time]['year'].to_i ,params[:start_time]['month'].to_i ,params[:start_time]['day'].to_i ,params[:start_time]['hour'].to_i ,00,00)
      @search_end_time = @search_start_time + @duration.to_i().hours
      subquery = Room.joins("LEFT OUTER JOIN bookings on rooms.id = bookings.room_id").where("((? >= bookings.start AND ? < bookings.end ) OR ( ? > bookings.start AND ? <= bookings.end ))", @search_start_time, @search_start_time, @search_end_time, @search_end_time).distinct.select('rooms.room_number')
      if @size != 'Any' and @building != 'Any'
        @rooms = Room.where(" room_number not in (?)", subquery).where(" size = ?", @size).where(" building = ?", @building)
      elsif @size != 'Any'
        @rooms = Room.where(" room_number not in (?)", subquery).where(" size = ?", @size)
      elsif @building != 'Any'
        @rooms = Room.where(" room_number not in (?)", subquery).where(" building = ?", @building)
      else
        @rooms = Room.where(" room_number not in (?)", subquery)
      end
    end
  end

  def bookroom
  end


  def roomhistory
    @history = Booking.where(room_id: params[:id]).order(:start)
  end
  def userhistory
    @history = Booking.where(library_member_id: params[:id]).order(:start)
  end
  # POST /bookings
  # POST /bookings.json
  def create
    subquery = Booking.where(library_member_id: params[:booking][:library_member_id]).where("((? >= bookings.start AND ? < bookings.end ) OR ( ? > bookings.start AND ? <= bookings.end ))", DateTime.parse(params[:booking][:start]), DateTime.parse(params[:booking][:start]), DateTime.parse(params[:booking][:end]), DateTime.parse(params[:booking][:end])).first
    @booking = Booking.new(booking_params)
    if subquery and !current_user.admin?
      respond_to do |format|
        @booking.errors.add(:you, " cannot book 2 rooms at the same time")
        format.html { render :search }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    else
      respond_to do |format|
        if @booking.save
          temp_emails = params[:booking][:emails] #.split(',').strip(' ')
          UserNotifierMailer.send_signup_email(temp_emails, @booking).deliver
          @library_member = LibraryMember.find(params[:booking][:library_member_id])
          format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
          format.json { render :show, status: :created, location: @booking }
        else
          format.html { render :search }
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:start, :end, :room_id, :library_member_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if params and params.key?('start_time') %>
  <div class="field">
    <%= f.label :start %>
    <%= f.hidden_field :start, :value => DateTime.parse(params['start_time']) %>
    <%= DateTime.parse(params['start_time']).strftime("%Y-%b-%d %I%p") %>
  </div>
    <% end %>
    <% if params and params.key?('end_time') %>
  <div class="field">
    <%= f.label :end %>
    <%= f.hidden_field :end, :value => DateTime.parse(params['end_time']) %>
    <%= DateTime.parse(params['end_time']).strftime("%Y-%b-%d %I%p") %>
  </div>
    <% end %>
  <div class="field">
    <%= f.label :room_id %>
    <%= f.hidden_field :room_id, :value => params['room'] %>
    <%= params['room'] %>
  </div>

  <div class="field">
  <% if current_user.admin? %>
    <%= f.label :library_member_id %>
  <%= collection_select(:booking, :library_member_id, LibraryMember.where(admin: [false, nil]), :id, :email) %>
  <% else %>
    <%= f.label :library_member_id %>
    <%= f.hidden_field :library_member_id, :value => current_user.id %>
    <%= current_user.email %>
  <% end %>
  </div>

  <div class="field">
    <%= f.label :emails %>
    <%= f.text_field :emails, class: 'form-control'  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/bookroom.html.erb
<p id="notice"><%= notice %></p>
<%if @rooms.empty? %>
    <p>There are no rooms.</p>
<%end%>
<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room number</th>
      <th>Size</th>
      <th>Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% params[:rooms].each do |room| %>
      <tr>
        <td><%= room.room_number %></td>
        <td><%= room.size %></td>
        <td><%= room.building %></td>
        <td><%= link_to 'Book',edit_room_path(room) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', bookings_search_path %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Room</th>
      <th>Library member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.start.strftime("%Y-%b-%d %I%p") %></td>
        <td><%= booking.end.strftime("%Y-%b-%d %I%p") %></td>
        <td><%= booking.room.id %></td>
        <td><%= booking.library_member.email %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', bookings_search_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_search_path %>

app/views/bookings/roomhistory.html.erb
<p id="notice"><%= notice %></p>

<h1>Room Booking History</h1>

<table>
  <thead>
  <tr>
    <th>Start</th>
    <th>End</th>
    <th>Room</th>
    <th>Library member</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @history.each do |booking| %>
      <tr>
        <td><%= booking.start.strftime("%Y-%b-%d %I%p") %></td>
        <td><%= booking.end.strftime("%Y-%b-%d %I%p") %></td>
        <td><%= booking.room.room_number %></td>
        <td><%= booking.library_member.email %></td>
        <td><%= link_to 'Show', booking %></td>
        <% if (booking.start >= Time.now - 4.hours) %>
            <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', bookings_search_path %>

app/views/bookings/search.html.erb
<h1> Search for available rooms</h1>
<%= form_tag bookings_search_path, :method => 'get' do %>

    <% if defined?(@booking) and @booking.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this room from being saved:</h2>

          <ul>
            <% @booking.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= label_tag :"start time" %>
      <% if defined?(@search_start_time) %>
          <%= select_datetime(@search_start_time, :discard_minute => true, :prefix => :start_time) %>
      <% else %>
        <%= select_datetime(Time.now - 3.hours, :discard_minute => true, :prefix => :start_time) %>
      <% end %>
</div>
    <div>
      <%= label_tag :"Duration" %>
      <% if defined?(@duration) and @duration == '2' %>
          1 hour
          <%= radio_button_tag :duration, '1' %> 2 hour
          <%= radio_button_tag :duration, '2', true %>
      <% else %>
      1 hour
      <%= radio_button_tag :duration, '1', true  %> 2 hour
      <%= radio_button_tag :duration, '2' %>
      <% end %>

</div>
    <div>
      <%= label_tag :"Size" %>
      <% if defined?(@size) and @size == 'Small' %>
          Small (4 members)
          <%= radio_button_tag :size, 'Small', true %> Medium (6 members)
          <%= radio_button_tag :size, 'Medium' %> Large (12 members)
          <%= radio_button_tag :size, 'Large' %> Any
          <%= radio_button_tag :size, 'Any' %>
      <% elsif defined?(@size) and @size == 'Medium' %>
          Small (4 members)
          <%= radio_button_tag :size, 'Small' %> Medium (6 members)
          <%= radio_button_tag :size, 'Medium', true %> Large (12 members)
          <%= radio_button_tag :size, 'Large' %> Any
          <%= radio_button_tag :size, 'Any' %>
      <% elsif defined?(@size) and @size == 'Large' %>
          Small (4 members)
          <%= radio_button_tag :size, 'Small' %> Medium (6 members)
          <%= radio_button_tag :size, 'Medium' %> Large (12 members)
          <%= radio_button_tag :size, 'Large', true %> Any
          <%= radio_button_tag :size, 'Any' %>
      <% else %>
          Small (4 members)
          <%= radio_button_tag :size, 'Small' %> Medium (6 members)
          <%= radio_button_tag :size, 'Medium' %> Large (12 members)
          <%= radio_button_tag :size, 'Large' %> Any
          <%= radio_button_tag :size, 'Any', true %>
      <% end %>

    </div>
    <div>

      <%= label_tag :"Building" %>
      <% if defined?(@building) and @building == 'D.H.Hill' %>
          D.H.Hill
          <%= radio_button_tag :building, 'D.H.Hill', true %> James.B.Hunt
          <%= radio_button_tag :building, 'James.B.Hunt' %> Any
          <%= radio_button_tag :building, 'Any' %>
      <% elsif defined?(@building) and @building == 'James.B.Hunt' %>
          D.H.Hill
          <%= radio_button_tag :building, 'D.H.Hill' %> James.B.Hunt
          <%= radio_button_tag :building, 'James.B.Hunt', true %> Any
          <%= radio_button_tag :building, 'Any' %>
      <% else %>
          D.H.Hill
          <%= radio_button_tag :building, 'D.H.Hill' %> James.B.Hunt
          <%= radio_button_tag :building, 'James.B.Hunt' %> Any
          <%= radio_button_tag :building, 'Any', true %>
      <% end %>

    </div>
    <%= submit_tag "Search" %>
<% end %>

<p id="notice"><%= notice %></p>
<%if not defined?(@rooms) or @rooms.empty? %>
    <p>There are no rooms.</p>
<%else%>
<h1>Rooms</h1>

<table>
  <thead>
  <tr>
    <th>Room number</th>
    <th>Size</th>
    <th>Building</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_number %></td>
        <td><%= room.size %></td>
        <td><%= room.building %></td>
        <td><%= link_to 'Book',new_booking_path(:room => room, :start_time => @search_start_time, :end_time => @search_end_time) %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>
<br>




<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Start:</strong>
  <%= (@booking.start + 0.hours).strftime("%Y-%b-%d %I%p") %>
</p>

<p>
  <strong>End:</strong>
  <%= (@booking.end + 0.hours).strftime("%Y-%b-%d %I%p") %>
</p>

<p>
  <strong>Room:</strong>
  <%= @booking.room.room_number %>
</p>

<p>
  <strong>Library member:</strong>
  <%= @booking.library_member.email %>
</p>

<%= link_to 'Back', bookings_search_path %>

app/views/bookings/userhistory.html.erb
<p id="notice"><%= notice %></p>

<h1>User Booking History</h1>

<table>
  <thead>
  <tr>
    <th>Start</th>
    <th>End</th>
    <th>Room</th>
    <th>Library member</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @history.each do |booking| %>
      <tr>
        <td><%= (booking.start - 0.hours).strftime("%Y-%b-%d %I%p") %></td>
        <td><%= (booking.end - 0.hours).strftime("%Y-%b-%d %I%p") %></td>
        <td><%= booking.room.room_number %></td>
        <td><%= link_to 'Show', booking %></td>
        <% if (booking.start >= Time.now - 4.hours) %>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', bookings_search_path %>