config/routes.rb
Rails.application.routes.draw do


  get 'bookings/search'
  post 'bookings/search', to: 'bookings#search_post'
  get 'bookings/bookroom'
  get '/roomhistory/:id', to: 'bookings#roomhistory',  via: :get, as: :room_history
  get '/userhistory/:id', to: 'bookings#userhistory', via: :get, as: :user_history
  get '/index_admin', to: 'library_members#index_admin'
  get '/new_admin', to: 'library_members#new_admin'
  get '/new_admin_library_member', to: 'library_members#new_admin_library_member'
  post '/index_admin', to: 'library_members#create_admin'
  resources :bookings
  resources :rooms
  get 'sessions/new'
  #get 'library_members/new'
  resources :library_members
  get 'static_pages/home'
  get  '/signup',  to: 'library_members#new'
  get 'static_pages/help'
  get 'static_pages/about'
  root 'static_pages#home'
  post '/signup',  to: 'library_members#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings, :dependent => :delete_all
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])
    @temp_room = Room.joins("LEFT OUTER JOIN bookings on rooms.id = bookings.room_id").
        joins("LEFT OUTER JOIN library_members on bookings.library_member_id = library_members.id")
                .where(" ((? between bookings.start and bookings.end) or bookings.start is null) and rooms.id = ?", Time.now - 4.hours, params[:id]).
        select("rooms.*", "library_members.email").distinct().first
    if @temp_room
      @room = @temp_room
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_number, :size, :building)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <div class="field">
    <%= f.label :room_number %>
    <%= f.number_field :room_number %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.select :size, [['Small - 4 chairs','Small'],['Medium - 6 chairs','Medium'],['Large - 12 chairs','Large']] %>
  </div>

  <div class="field">
    <%= f.label :building %>
    <%= f.select :building, [['D.H.Hill','D.H.hill'],['James.B.Hunt','James.B.Hunt']] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room number</th>
      <th>Size</th>
      <th>Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_number %></td>
        <td><%= room.size %></td>
        <td><%= room.building %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'History', room_history_path(room) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Room number:</strong>
  <%= @room.room_number %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.size %>
</p>

<p>
  <strong>Building:</strong>
  <%= @room.building %>
</p>

<% if current_user.admin? and @room.has_attribute?(:email) and @room.email %>
<p>
  <strong>Currently booked by Library Member:</strong>
  <%= @room.email %>
</p>
<% end %>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>