config/routes.rb
Rails.application.routes.draw do


  get 'bookings/search'
  post 'bookings/search', to: 'bookings#search_post'
  get 'bookings/bookroom'
  get '/roomhistory/:id', to: 'bookings#roomhistory',  via: :get, as: :room_history
  get '/userhistory/:id', to: 'bookings#userhistory', via: :get, as: :user_history
  get '/index_admin', to: 'library_members#index_admin'
  get '/new_admin', to: 'library_members#new_admin'
  get '/new_admin_library_member', to: 'library_members#new_admin_library_member'
  post '/index_admin', to: 'library_members#create_admin'
  resources :bookings
  resources :rooms
  get 'sessions/new'
  #get 'library_members/new'
  resources :library_members
  get 'static_pages/home'
  get  '/signup',  to: 'library_members#new'
  get 'static_pages/help'
  get 'static_pages/about'
  root 'static_pages#home'
  post '/signup',  to: 'library_members#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://www.lib.ncsu.edu/">NCSU Library</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  static_pages_about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "NC STATE Library", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
            <% if current_user.admin? %>
                <li><%= link_to "Manage Rooms", rooms_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Manage Users <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Create Admin", new_admin_path %></li>
                    <li><%= link_to "View Admin", index_admin_path %></li>
                    <li><%= link_to "Create Library Member", new_admin_library_member_path %></li>
                  </ul>
                </li>
                <li><%= link_to "Members", library_members_path %></li>
            <% end %>
            <li><%= link_to "Book Rooms", bookings_search_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>

                <li><%= link_to "Settings", edit_library_member_path(current_user) %></li>

                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>